In [53]:
n = 10
n

10

In [54]:
n = 10
z = 5
n
z

5

In [55]:
print(n)
print(z)

10
5


In [56]:
b = n + z
b

15

***data science***

In [57]:
n = [1,2,3,4,5,6]
n

[1, 2, 3, 4, 5, 6]

In [58]:
z = n*2

In [59]:
z

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [60]:
g = [1,2,3,4,5]

In [61]:
g*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [2]:
c = [1,2,3,4,5,6]
c

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np

In [4]:
d = np.array(c)
d

array([1, 2, 3, 4, 5, 6])

In [5]:
d*2

array([ 2,  4,  6,  8, 10, 12])

In [6]:
my_list = [-1,0,1]
my_list 
my_list[0]

-1

In [7]:
my_list = [-1,0,1]
my_list 
my_list[0]

-1

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9],[4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [9]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [10]:
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
np.linspace(0.055,0.99,150,retstep = True)

(array([0.055     , 0.06127517, 0.06755034, 0.0738255 , 0.08010067,
        0.08637584, 0.09265101, 0.09892617, 0.10520134, 0.11147651,
        0.11775168, 0.12402685, 0.13030201, 0.13657718, 0.14285235,
        0.14912752, 0.15540268, 0.16167785, 0.16795302, 0.17422819,
        0.18050336, 0.18677852, 0.19305369, 0.19932886, 0.20560403,
        0.21187919, 0.21815436, 0.22442953, 0.2307047 , 0.23697987,
        0.24325503, 0.2495302 , 0.25580537, 0.26208054, 0.2683557 ,
        0.27463087, 0.28090604, 0.28718121, 0.29345638, 0.29973154,
        0.30600671, 0.31228188, 0.31855705, 0.32483221, 0.33110738,
        0.33738255, 0.34365772, 0.34993289, 0.35620805, 0.36248322,
        0.36875839, 0.37503356, 0.38130872, 0.38758389, 0.39385906,
        0.40013423, 0.4064094 , 0.41268456, 0.41895973, 0.4252349 ,
        0.43151007, 0.43778523, 0.4440604 , 0.45033557, 0.45661074,
        0.46288591, 0.46916107, 0.47543624, 0.48171141, 0.48798658,
        0.49426174, 0.50053691, 0.50681208, 0.51

In [17]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

In [18]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(30)

array([0.5829125 , 0.47671108, 0.89315681, 0.63760305, 0.63290026,
       0.18706501, 0.50276301, 0.2766636 , 0.73842607, 0.61419426,
       0.53580715, 0.85931274, 0.02724116, 0.85029416, 0.23953662,
       0.90526864, 0.99535304, 0.74155552, 0.26146333, 0.27020376,
       0.1734484 , 0.33813781, 0.95799985, 0.44334805, 0.32572236,
       0.21346486, 0.85359861, 0.57278317, 0.98410132, 0.05977956])

In [23]:
np.random.rand(3,2)

array([[0.67286518, 0.56353059],
       [0.46979165, 0.50966678],
       [0.89452526, 0.13037776]])

In [24]:
np.random.randint(1,100)

13

In [25]:
np.random.randn(100,100)

array([[-0.7192032 , -0.00937282, -0.05469108, ...,  0.83585561,
        -0.37549309, -0.27797232],
       [ 0.3537836 , -0.10177999,  1.17839066, ...,  0.15757522,
         0.25779006, -2.23025527],
       [ 0.40382276, -0.44833436, -0.12885705, ...,  0.19358327,
         1.44098431, -0.29083206],
       ...,
       [-0.95614146,  0.34346588,  0.36210082, ...,  0.7303458 ,
         0.03272215,  0.6990277 ],
       [ 1.75953281,  2.08888554,  0.52153605, ...,  0.38117123,
        -0.15899158,  0.20397121],
       [-0.07274839, -0.85992341,  1.5662713 , ..., -1.57962761,
        -0.4831761 ,  0.24840969]], shape=(100, 100))

In [28]:
array_arange = np.arange(0,16)
array_ranint = np.random.randint(0,100,10)

In [29]:
array_ranint

array([31, 41, 25, 13, 68, 81,  6, 72, 97, 20], dtype=int32)

In [30]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
array_ranint.max()

np.int32(97)

In [32]:
array_ranint.argmax()

np.int64(8)

In [33]:
array_ranint.argmin()

np.int64(6)

In [34]:
array_arange.shape

(16,)

In [35]:
array_arange.size

16

In [36]:
array_arange.dtype

dtype('int64')

In [37]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
array_arange.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [39]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [40]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [41]:
array_1d[0]

np.int64(-10)

In [42]:
array_1d[0:3], array_1d

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [43]:
array_2d= np.arange(24)
array_2d.shape = (6,4) #array_2d.reshape(6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])